<!-- Nadpis ------------------------------------------------------------------->

<?php $this->title = "Změna hesla"; ?>

<!-- JavaScript --------------------------------------------------------------->

<script type="text/javascript">
//<![CDATA[    
$(document).ready(function() {
    
    $('input:submit').button();
});
//]]>    
</script>

<!-- Obsah stránky ------------------------------------------------------------>

<?php if ($this->exceptionMessage): ?>
    <div class="ui-widget errorDiv">
        <div class="ui-state-error ui-corner-all">
            <p><span class="ui-icon ui-icon-alert"></span>
            <strong>Heslo se nepodařilo změnit:</strong> <?php echo $this->exceptionMessage; ?></p>
        </div>
    </div>
<?php endif; ?>

<?php echo $this->form; ?>