<!-- Nadpis ------------------------------------------------------------------->

<?php $this->title = "Změna hesla"; ?>

<!-- JavaScript --------------------------------------------------------------->

<script type="text/javascript">
//<![CDATA[    
$(document).ready(function() {
    
    $('input:submit').button();
});
//]]>    
</script>

<!-- Obsah stránky ------------------------------------------------------------>

<?php echo $this->form; ?>