<p>Potvrďte, že chcete smazat následující záznam</p>

<table class="standardni odsazene-bunky">
    <tr>
        <th>Datum směny</th>
        <th>Příchod</th>
        <th>Odchod</th>
    </tr>
    <tr>
        <td><?php echo $this->data['datumSmeny']; ?></td>
        <td><?php echo $this->data['prichodDen'].' '.$this->data['prichodCas']; ?></td>
        <td><?php echo $this->data['odchodDen'].' '.$this->data['odchodCas']; ?></td>
    </tr>
</table>