<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {     
    // změna pauzy nebude realizována odesláním formuláře
    $('#form-dochazka-zapisOficialniPauzy').submit(function(){               
        return false;
    });
    
    $('.button-nahoru').button({
        icons: {primary: 'ui-icon-arrowthick-1-n'},
        text: false
    });     
    $('.button-dolu').button({
        icons: {primary: 'ui-icon-arrowthick-1-s'},
        text: false
    });  
});
//]]>    
</script>

<h3>Záznamy z vybraného dne</h3>

<table>
    <tr>
        <td class="padding-right-10">Datum</td>
        <td><?php echo $this->data['datum']; ?></td>
    </tr>
    <tr>
        <td class="padding-right-10">Průchody</td>
        <td>
            <?php if (count($this->data['pruchody'])>0):?>

                <?php foreach ($this->data['pruchody'] as $pruchod): ?>
                <?php echo $pruchod['casPrichod'].' - '.$pruchod['casOdchod'].'<br />'; ?>
                <?php endforeach; ?>

            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td class="padding-right-10">Suma pauzy</td>
        <td>
            <?php if (count($this->data['preruseni'])>0): ?>
                <?php echo $this->data['preruseni'][0]['delka']; ?> h
            <?php endif; ?>
        </td>
    </tr>
</table>

<div class="ui-widget smallInfoDiv">
    <div class="ui-state-highlight ui-corner-all">
        <p><span class="ui-icon ui-icon-info"></span>
        <strong>Klávesové zkratky</strong><br />Mezi dny se můžete
        pohybovat klávesami <button class="button-nahoru">&nbsp;</button> a
        <button class="button-dolu">&nbsp;</button></p>
    </div>
</div>   

<h3>Změna sumy pauzy</h3>

<?php echo $this->form; ?>
