<p>Potvrďte, že chcete smazat následující záznam</p>

<table class="standardni odsazene-bunky">
    <tr>
        <th>Datum směny</th>
        <th>Příchod</th>
        <th>Odchod</th>
    </tr>
    <tr>
        <td><?php echo $this->data['datumSmeny']; ?></td>
        <td><?php echo $this->data['denPrichod'].' '.$this->data['hodPrichod']; ?></td>
        <td><?php echo $this->data['denOdchod'].' '.$this->data['hodOdchod']; ?></td>
    </tr>
</table>