<?php $this->title = "Doplnění přílatků docházky ($this->uzivatel)"; ?>

<script type="text/javascript">
//<![CDATA[    

$(document).ready(function() {
    
    $('input:submit').button(); 

});
//]]>    
</script>

<div class="ui-widget infoDiv">
    <div class="ui-state-highlight ui-corner-all">
        <p><span class="ui-icon ui-icon-info"></span>
        Nechcete-li nějaký z filtrů použít, klikněte na tlačítko "Zakázat/povolit"</p>
    </div>
</div>      

