<?php $this->title = "Vytvoření oficiálního výkazu docházky ($this->uzivatel)"; ?>

<script type="text/javascript">
//<![CDATA[    
$(document).ready(function() {
    $('.monthpicker').monthpicker({
        showOn: "focus",
        yearRange: 'c-1:c',
        regional: 'cs'
    });
    
    $('input:submit').button();
});
//]]>    
</script>

<div class="ui-widget infoDiv">
    <div class="ui-state-highlight ui-corner-all">
        <p><span class="ui-icon ui-icon-info"></span>
        Vytvořit výkaz docházky je vhodné až po skončení daného měsíce
        (další data by bylo nutné dopsat ručně)</p>
    </div>
</div>   

<p>Měsíc, pro který bude tvořen výkaz</p>
<?php echo $this->form; ?>