<?php $this->title = "Změna oficiálního výkazu docházky ($this->uzivatel)"; ?>
<?php $this->obrazekStredni = "clovek.png"; ?>

<script type="text/javascript">
//<![CDATA[    

$(document).ready(function() {
    
    $('#dochazka-officialZakorouhleniCasu').button({
        icons: {primary: 'ui-icon-clock'}
    }); 
    
    $('.dochazka-officialZmenaCasu').button({
        icons: {primary: 'ui-icon-search'},
        text: false
    });
    
    $('.dochazka-officialSmazaniCasu').button({
        icons: {primary: 'ui-icon-trash'},
        text: false
    });
    
    $('.dochazka-officialPridaniCasu').button({
        icons: {primary: 'ui-icon-plus'},
        text: false
    });
    
    /**** AJAXOVÉ POČÍTÁNÍ ČASŮ ***********************************************/
     
    $.ajax({      
        type: "POST",
        url: "<?php echo $this->url(array('module'=>'dochazka','controller'=>'official','action' => 'ajax-pocitani-casu'),null,true);?>",
        data: ({id: <?php echo $this->idVykazu; ?>}),        
        dataType: 'json',
        success: function(data) { 
       
            var i = 0;
            for ( i == 0; i <= (data.length -1); i++) {
                
                $('#officialni-dochazka-dochazka-'+i).html(data[i]['dochazka']);
                $('#officialni-dochazka-pauza-'+i).html(data[i]['pauza']);
                $('#officialni-dochazka-cistaDochazka-'+i).html(data[i]['cistaDochazka']);                
            }
        }
    });                
    
    /***************************************************************************
     * Modální dialog pro mazání jednotlivých časů z oficiální docházky
     */
     $('.dochazka-officialSmazaniCasu').click(function(event){
    
        // hack, aby se stránka neodscrollovala nahoru
        event.preventDefault();    
    
        var id = $(this).attr('id');
    
        // do DIVu zobrazíme data o mazaném záznamu
        $.ajax({      
            type: "POST",
            url: "<?php echo $this->url(array('module'=>'dochazka','controller'=>'official','action' => 'ajax-mazani-zaznamu'),null,true);?>",
            data: ({id: id}),          
            success: function(data) { 
                $("#div-dochazka-officialSmazaniCasu").html(data);
            }
        });            
        
        // vykreslíme dialogové okno
        $("#div-dochazka-officialSmazaniCasu").dialog({            
            modal: true,
            width: 600,
            height: 400,        
            buttons: {
                "Smazat": function() {   
                    
                    // provedení smazání času příchodu a odchodu
                    $.ajax({      
                        type: "POST",
                        url: "<?php echo $this->url(array('module'=>'dochazka','controller'=>'official','action' => 'ajax-mazani-pruchodu'),null,true);?>",
                        data: ({id: id}),        
                        success: function() {   
                            location.reload();
                        }
                    });                                         
                    $( this ).dialog( "close" );               
                },
                "Zrušit": function() {
                    $( this ).dialog( "close" );
                }
            }               
        });
    });           
    
});
//]]>    
</script>

<a href ="<?php echo $this->url(array('module' => 'dochazka',
                  'controller' => 'official',
                  'action' => 'zaokrouhleni-prichodu',
                  'id' => $this->idVykazu)); ?>"
   id="dochazka-officialZakorouhleniCasu">
    Zaokrouhlení příchodů
</a>

<table class="standardni odsazene-bunky margin-top-10">
    <tr>
        <th>Datum</th>
        <th>Docházka</th>
        <th>Suma<br />práce</th>
        <th>Suma<br />pauzy</th>
        <th>Čistá<br />práce</th>
        <?php foreach ($this->typyPriplatku as $typPriplatku): ?>
        <th><?php echo $typPriplatku['zkratka']; ?></th>
        <?php endforeach; ?>
        <th>Poznámka</th>
    </tr>

<?php foreach ($this->data as $i => $zaznam): ?>
    <tr>
        <td>
            <?php echo $zaznam['datum']; ?>
            <a href ="<?php echo $this->url(array('module' => 'dochazka',
                  'controller' => 'official',
                  'action' => 'pridani-pruchodu',
                  'den' => $zaznam['dbDatum'])); ?>"
               class="dochazka-officialPridaniCasu">
                &nbsp;
            </a>
        </td>
        <td>
            <table style="padding: 0; margin: 0;">
            <?php foreach ($zaznam['pruchody'] as $pruchod): ?>         
                <tr>
                    <td> 
                        <?php echo $pruchod['shortCasPrichod']; ?> - 
                        <?php echo $pruchod['shortCasOdchod']; ?>
                        <a href ="<?php echo $this->url(array('module' => 'dochazka',
                                'controller' => 'official',
                                'action' => 'zmena-pruchodu',
                                'idZaznamu' => $pruchod['id'])); ?>"                         
                           class="dochazka-officialZmenaCasu">
                            &nbsp;
                        </a>
                        <a href="#"
                           id="<?php echo $pruchod['id']; ?>"
                           class="dochazka-officialSmazaniCasu">
                            &nbsp;
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </table>
        </td>
        <td id="officialni-dochazka-dochazka-<?php echo $i; ?>"></td>
        <td id="officialni-dochazka-pauza-<?php echo $i; ?>"></td>
        <td id="officialni-dochazka-cistaDochazka-<?php echo $i; ?>"></td>        
    <?php 
        // projedeme všechny příplatky podle typu, pro každý vypíšeme buňku tabulky
        foreach ($this->typyPriplatku as $typPriplatku):
    ?>
        <td>
        <?php
            // pokud máme nějaký zapsaný příplatek, časem ho vypíšeme
            if (!empty($zaznam['priplatky'])) {
                foreach ($zaznam['priplatky'] as $priplatek) {
              
                    // pokud se shoduje typ příplatku se zapsaným příplatkem, vypíšeme jej právě teď
                    if ($typPriplatku['id'] == $priplatek['idPriplatku']) {           
                        echo $priplatek['delka']; 
                    }
                }
            } ?>
        </td>
    <?php endforeach; ?>
        <td>
            <?php 
            // poznámka bude z proncipu věci jenom jedna
            if (!empty($zaznam['poznamka'])) {
                echo $zaznam['poznamka'][0]['text'];
            } ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<!-- Dialogový DIV pro mazání záznamů docházky -------------------------------->

<div id="div-dochazka-officialSmazaniCasu"
     title="Smazání záznamu oficiální docházky">        
    
</div>