
<script type="text/javascript">
//<![CDATA[    


$(document).ready(function() {
    
   $('#aa').datepicker();
   $('#bb').datepicker();
   
   
    /***************************************************************************
     * Modální dialog pro změnu průchodu (dvojice příchod - odchod)
     */
    $('#dochazka-oficialni-zmenaPruchodu').click(function(event){
    
        
         // vykreslíme dialogové okno
            $('#aaa').dialog('open');
    });
    
    $("#aaa").dialog({  
            autoOpen: false,
            width: 500,
           
            resizable: false,       
            open: function() {

            },
            buttons: {
                "Změnit": function() {   

                },
                "Zrušit": function() {
                    $( this ).dialog( "close" );
                }
            }               
        });    
    
});
//]]>    
</script>

<button id="dochazka-oficialni-zmenaPruchodu">asdf</button>

<!-- Dialogový DIV pro změnu průchodu ----------------------------------------->

<div id="aaa">    

    <form>
        <input name="aa" type="text" id="aa" />
        <input name="bb" type="text" id="bb" />
     
    </form>     
</div>

