<!-- Nadpis ------------------------------------------------------------------->

<?php $this->title = "Přidání časového záznamu"; ?>

<!-- Obsah stránky ------------------------------------------------------------>

<script type="text/javascript">
//<![CDATA[  


/**
 * Do prnvího prázdného ID inputu nakopírujeme získané ID
 * 
 * @return boolean Pokud se nepodařilo vyplnit, vrátí false
 */
function vyplnId() {
            
    var i=0;
    for (i==0; i<20; i++) {
        var id = $("#id-"+i).val();
        if (typeof(id) != "undefined" && id.length == 0) {
            $("#id-"+i).val($("#naspetavacPozice").val());
            return true;
            break;
        };
    }                   
    return false;
}

$(function() {
    var display = '<?php echo $this->display; ?>';
    switch (display) {
        case 'vyroba':
            $( "#div-vyroba-addZapis" ).accordion();
            $( "#div-vyroba-zaznamovyDiv").tabs();
            break;
        case 'rezie':
            $( "#div-vyroba-addZapis" ).accordion({ active: 1 });
            $( "#div-vyroba-zaznamovyDiv").tabs({ selected: 1 });
            break;            
    }   
});



$(document).ready(function() {
    
    $('a.odkaz').button();
    $('input:submit').button();  
    $('#pridejRadek').button({icons: {primary: 'ui-icon-circle-plus'}});
    $('#zjistiID').button({icons: {primary: 'ui-icon-help'}});
    
    $("#vyroba-div-zapisVyrobyDily").tabs();
    $("#vyroba-div-zapisVyrobyPrace").tabs();
    $("#vyroba-div-zapisVyrobyUkony").tabs();     
    $("#vyroba-div-zapisReziePrace").tabs();
    $("#vyroba-div-zapisRezieUkony").tabs();
    
    /**
     * Odeslání výrobního formuláře - provedeme validaci předem, synchronně,
     * aby bylo monžno zabránit návratu
     */
    $("#form-vyroba-vyrobaForm").submit(function(){
        
        var navrat = true;
        
        $.ajax({
            async: false,
            type: "POST",
            url: "<?php //echo $this->url(array('action' => 'ajax-form-vyroba-check'));?>",
            data: ($(this).serialize()),
            success: function(chyboveHlaseni) {
                if (chyboveHlaseni.length > 0) {
                    
                    $("#div-vyroba-messageDiv").html(chyboveHlaseni);
                    $("#div-vyroba-messageDiv").fadeIn(500);
                    navrat = false;
                }       
            }
        });
        
        return navrat;
    });
    
    /**
     * Odeslání režijního formuláře - provedeme validaci předem, synchronně,
     * aby bylo monžno zabránit návratu
     */
    $("#form-vyroba-rezieForm").submit(function(){
        
        var navrat = true;
        
        $.ajax({
            async: false,
            type: "POST",
            url: "<?php echo $this->url(array('action' => 'ajax-form-rezie-check'));?>",
            data: ($(this).serialize()),
            success: function(chyboveHlaseni) {
                if (chyboveHlaseni.length > 0) {
                    
                    $("#div-vyroba-messageDiv").html(chyboveHlaseni);
                    $("#div-vyroba-messageDiv").fadeIn(500);
                    navrat = false;
                }       
            }
        });
        
        return navrat;
    });
        
    
    /**
     * Přidání řádku ID pozice do formuláře po kliku na tlačítko "přidat řádek"
     */
    $("#pridejRadek").click(function(){
       
        var pocet = $("#pocetRadku").val();

        $.ajax({

            type: "POST",
            url: "<?php echo $this->url(array('action' => 'ajax-novy-radek'));?>",
            data: ({pocet: pocet}),
            success: function(newElement) {
        
              // vložíme nový element na správné místo stránky, focus na něj
              $("#idZaznamu-label").before(newElement);
              $("#id-"+pocet).focus();
              
              // inkrementujeme počet řádků
              $("#pocetRadku").val(++pocet);
            }
        });
    });
    
    /**
     * Modální dialog pro zjištění ID pozice ze zadané zakázky a názvu pozice
     */
    $("#zjistiID").click(function(){
        $("#div-vyroba-hiddenIdNaseptavac").dialog({
            modal: true,
            width: 500,
            height: 350,
            buttons: {
                "Vyplnit ID a zavřít": function() {
                    var uspech = vyplnId();
                    if (!uspech) {
                        alert('Nepodařilo se vyplnit hodnotu, nejspíš chybí volné políčko');
                    }
                    $( this ).dialog( "close" );
                },                
                "Vyplnit ID a pokračovat": function() {
                    var uspech = vyplnId();
                    if (!uspech) {
                        alert('Nepodařilo se vyplnit hodnotu, nejspíš chybí volné políčko');
                    }
                },
                "Zrušit": function() {
                        $( this ).dialog( "close" );
                }
            }
        });     
    });

    $("#naseptavacZakazka").change(function(){
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url(array('action' => 'ajax-naseptavac'));?>",
            data: ({id: $("#naseptavacZakazka").val()}),
            success: function(element) {

                // smažeme starý výběr dílů
                $("#naspetavacPozice-element").remove();           
                $("#naspetavacPozice-label").remove();

                // přidáme nový výběr dílů
                $("#naseptavacZakazka-element").after(element);
            }
        });        
    });    
 
});

//]]>    
</script>

<div id="div-vyroba-addZapis">
    <h3>Zápis výrobních časů</h3>
    
    
    <div id="div-vyroba-addZapisVyroby">
        <form action="<?php echo $this->vyrobaForm->getAction(); ?>"
              method="<?php echo $this->vyrobaForm->getMethod(); ?>"
              id="<?php echo $this->vyrobaForm->getId(); ?>">
            
        
        <div id="vyroba-div-zapisVyrobyDily"
             class="ui-widget ui-widget-content ui-corner-all ui-tabs vyroba-zapisVyrobyDiv">
            
            <ul><li><a href="#tabs-vyroba-dily">Identifiátor dílů</a></li></ul>         
            <div id="tabs-vyroba-dily">
                <?php echo $this->vyrobaForm->getDisplayGroup('dily'); ?>       
            </div>
        </div>
        <div id="vyroba-div-zapisVyrobyPrace"
             class="ui-widget ui-widget-content ui-corner-all ui-tabs vyroba-zapisVyrobyDiv">            
            <ul>
                <li><a href="#tabs-vyroba-prace">Určení činnosti</a></li>
            </ul>  
            <div id="tabs-vyroba-prace">
                <?php echo $this->vyrobaForm->getDisplayGroup('prace'); ?>       
            </div>
        </div>
        <div id="vyroba-div-zapisVyrobyUkony"
             class="ui-widget ui-widget-content ui-corner-all ui-tabs vyroba-zapisVyrobyDiv">
            <ul>
                <li><a href="#tabs-vyroba-ukony">Výrobní operace</a></li>
            </ul>  
            <div id="tabs-vyroba-ukony">
                <?php echo $this->vyrobaForm->getDisplayGroup('ukony'); ?>    
            </div>
        </div>
        </form>
    </div>
        
    <h3>Zápis režijních časů</h3>
    <div id="div-vyroba-addZapisRezie">
        <form action="<?php echo $this->rezieForm->getAction(); ?>"
              method="<?php echo $this->rezieForm->getMethod(); ?>"
              id="<?php echo $this->rezieForm->getId(); ?>">
            
        
        <div id="vyroba-div-zapisReziePrace"
             class="ui-widget ui-widget-content ui-corner-all ui-tabs vyroba-zapisVyrobyDiv">            
            <ul>
                <li><a href="#tabs-rezie-prace">Určení činnosti</a></li>
            </ul>                
            <div id="tabs-rezie-prace">
                <?php echo $this->rezieForm->getDisplayGroup('prace'); ?>       
            </div>
        </div>
        <div id="vyroba-div-zapisRezieUkony"
             class="ui-widget ui-widget-content ui-corner-all ui-tabs vyroba-zapisVyrobyDiv">
            <ul>
                <li><a href="#tabs-rezie-ukony">Režijní operace</a></li>
            </ul>
            <div id="tabs-rezie-ukony">
                <?php echo $this->rezieForm->getDisplayGroup('ukony'); ?>    
            </div>
        </div>
        </form>        
    </div>
</div>

<div id="div-vyroba-messageDiv"
     class="ui-state-error ui-corner-all">

    

</div>

<div id="div-vyroba-zaznamovyDiv">
    
    <ul>
        <li><a href="#div-vyroba-zaznamyVyroby">Posledních 10 výrobních časů</a></li>
        <li><a href="#div-vyroba-zaznamyRezie">Posledních 10 režijních časů</a></li>
    </ul>
    
    <div id="div-vyroba-zaznamyVyroby">
    <table class="table-vroba-tableZaznamy">
        <tr>
            <th>Jméno</th>
            <th>ID dílu</th>
            <th>Název dílu</th>
            <th>Zakázka</th>
            <th>Operace</th>
            <th>Datum</th>
            <th>Trvání (h)</th>
            <th>Zapsal</th>
            <th></th>
        </tr>        
        
        <?php if (count($this->vyrobniZaznamy) > 0): ?>
        <?php foreach ($this->vyrobniZaznamy as $radek): ?>

            <tr>
                <td><?php echo $radek['vyrobil']; ?></td>
                <td><?php echo $radek['idPozice']; ?></td>
                <td><?php echo $radek['dil']; ?></td>
                <td><?php echo $radek['zakazka']; ?></td>
                <td><?php echo $radek['operace']; ?></td>
                <td><?php echo $radek['datum']; ?></td>
                <td><?php echo $radek['casVyroby']; ?></td>
                <td><?php echo $radek['zapsal']; ?></td>
                <td>
                    <?php if ($radek['zmena']): ?>
                    <a class="odkaz"
                       href ="<?php echo $this->url(array('module' => 'vyroba',
                                                          'controller' => 'zapis',
                                                          'action' => 'edit-vyroba',
                                                          'zmena' => $radek['idZaznamu'],
                                                          'navrat' => 'add'),null,true); ?>">
                        Změnit
                    </a>  
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php endif; ?>                       
    </table>
    </div>
    
    <div id="div-vyroba-zaznamyRezie">
    <table class="table-vroba-tableZaznamy">
        <tr>
            <th>Jméno</th>
            <th>Typ režie</th>
            <th>Datum</th>
            <th>Trvání (h)</th>
            <th>Zapsal</th>
            <th>Poznámka</th>
            <th></th>
        </tr>
        
        <?php if (count($this->rezijniZaznamy) > 0): ?>
        <?php foreach ($this->rezijniZaznamy as $radek): ?>

            <tr>
                <td><?php echo $radek['vyrobil']; ?></td>
                <td><?php echo $radek['operace']; ?></td>
                <td><?php echo $radek['datum']; ?></td>
                <td><?php echo $radek['casTrvani']; ?></td>
                <td><?php echo $radek['zapsal']; ?></td>
                <td><?php echo $radek['poznamka']; ?></td>
                <td>
                    <?php if ($radek['zmena']): ?>
                    <a class="odkaz"
                       href ="<?php echo $this->url(array('module' => 'vyroba',
                                                          'controller' => 'zapis',
                                                          'action' => 'edit-rezie',
                                                          'zmena' => $radek['idZaznamu'],
                                                          'navrat' => 'add'),null,true); ?>">
                        Změnit
                    </a>     
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php endif; ?>                
    </table>
    </div>
</div>

<div id="div-vyroba-hiddenIdNaseptavac"
     title="Vyhledání ID dílu">
      
    <p>Vyberte zakázku a následně díl</p>
    
    <?php echo $this->naseptavacPozice; ?>
  
</div>