<?php $this->title = "Změna režijního času"; ?>

<script type="text/javascript">
//<![CDATA[  

$(function() {

    $( "#div-vyroba-zaznamovyDiv").tabs();
});

$(document).ready(function() {
    
    $('a.odkaz').button();
    $('input:submit').button();  

    $("#vyroba-div-zapisReziePrace").tabs();
    $("#vyroba-div-zapisRezieUkony").tabs()    
    
    /**
     * Odeslání režijního formuláře - provedeme validaci předem, synchronně,
     * aby bylo monžno zabránit návratu
     */
    $("#form-vyroba-rezieForm").submit(function(){
        
        var navrat = true;
        
        $.ajax({
            async: false,
            type: "POST",
            url: "<?php echo $this->url(array('action' => 'ajax-form-rezie-check'));?>",
            data: ($(this).serialize()),
            success: function(chyboveHlaseni) {
                if (chyboveHlaseni.length > 0) {
                    
                    $("#div-vyroba-messageDiv").html(chyboveHlaseni);
                    $("#div-vyroba-messageDiv").fadeIn(500);
                    navrat = false;
                }       
            }
        });
        
        return navrat;
    });
});

//]]>    
</script>

<div id="div-vyroba-addZapisRezie">
    <form action="<?php echo $this->rezieForm->getAction(); ?>"
          method="<?php echo $this->rezieForm->getMethod(); ?>"
          id="<?php echo $this->rezieForm->getId(); ?>">


    <div id="vyroba-div-zapisReziePrace"
         class="ui-widget ui-widget-content ui-corner-all ui-tabs vyroba-zapisVyrobyDiv">            
        <ul>
            <li><a href="#tabs-urceni-cinnosti">Určení činnosti</a></li>
        </ul>   
        <div id="tabs-urceni-cinnosti">
            <?php echo $this->rezieForm->getDisplayGroup('prace'); ?>       
        </div>
    </div>
    <div id="vyroba-div-zapisRezieUkony"
         class="ui-widget ui-widget-content ui-corner-all ui-tabs vyroba-zapisVyrobyDiv">
        <ul>
            <li><a href="#tabs-rezijni-operace">Režijní operace</a></li>
        </ul>  
        <div id="tabs-rezijni-operace">
            <?php echo $this->rezieForm->getDisplayGroup('ukony'); ?>    
        </div>
    </div>
    </form>        
</div>

<div id="div-vyroba-messageDiv"
     class="ui-state-error ui-corner-all">

</div>

<div id="div-vyroba-hiddenIdNaseptavac"
     title="Vyhledání ID dílu">
    
    <p>Vyberte zakázku a následně díl</p>
    <?php echo $this->naseptavacPozice; ?>
    
</div>