<!-- Nadpis -->
<?php $this->title = "Kontrolní tabulka ($this->uzivatel)"; ?>

<script type="text/javascript">
//<![CDATA[    
$(document).ready(function() {
    $('.zmenaButton').button();
});
//]]>    
</script> 

<table id="vyroba-time-tableKontrolaDilu"
           class="standardni">
    <tr>
        <th>Zakázka</th>
        <th>Díl</th>
        <th>Datum</th>
        <th>Trvání</th>
        <th>Začátek</th>
        <th>Operace</th>
        <th>Zdroj dat</th>
        <th>Karta</th>
        <th></th>
    </tr>

    <?php if (!empty($this->poleZaznamu)): ?>
    <?php foreach ($this->poleZaznamu as $zaznam): ?>
    <tr>
        <td><?php echo $zaznam['cisloZakazky']; ?></td>
        <td><?php echo $zaznam['nazevPozcie']; ?></td>
        <td><?php echo $zaznam['denStart']; ?></td>
        <td><?php echo $zaznam['trvani']; ?></td>
        <td><?php echo $zaznam['tinyCasStart']; ?></td>
        <td><?php echo $zaznam['technologie']; ?></td>
        <td><?php echo $zaznam['zdrojDat']; ?></td>
        <td><?php echo $zaznam['typPrace']; ?></td>
        <td>
            <a class="zmenaButton"
               href ="<?php echo $this->url(array('module' => 'vyroba',
                                                  'controller' => 'zapis',
                                                  'action' => 'edit-vyroba',
                                                  'zmena' => $zaznam['id'],
                                                  'navrat' => 'show-kontrola-vyroby'),null,true); ?>">
                Změnit
            </a>                                                     
        </td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>    
</table>